#!/bin/bash -e

usage() {
  echo "loeb - Linaro OpenEmbedded Builder"
  echo
  echo "Usage:"
  echo "  loeb setup    Set up host to build OpenEmbedded"
  echo "  loeb init     Initialize OpenEmbedded repository"
  echo "  loeb sync     Synchronize recipe repository with server"
  echo "  loeb apply    Apply a sauce"
  echo "  loeb reset    Reset everything to a pristine state"
}

log() {
  level=$1; shift
  msg=$*

  echo "[${level^^}] ${msg}"
}

log_on_error()
{
  local oldopts="$-"
  set +e
  logfile=$(mktemp -q)
  log info "Running [$*]"
  $* > ${logfile} 2>&1
  ret=$?
  if [ ${ret} -ne 0 ]; then
    cat "${logfile}"
  fi
  rm "${logfile}"
  set -${oldopts}
  return ${ret}
}

install_repo() {
  log info "Installing repo"
  mkdir -p "${HOME}/bin"
  curl -Ss https://storage.googleapis.com/git-repo-downloads/repo > "${HOME}/bin/repo"
  chmod a+x "${HOME}/bin/repo"
  if [ "${PATH}" != "${PATH/${HOME}\/bin\:}" ]; then
    export PATH="${HOME}/bin":"${PATH}"
  fi
}

get_repo_base_dir() {
  dir=$(readlink -e "$(repo info -l openembedded/bitbake 2> /dev/null | grep ^Mount | cut -d\  -f3)"/../)
  if [ -d "${dir}/.repo/" ]; then
    echo "${dir}"
  fi
}

loeb_setup() {
  SETUP_JENKINS=no
  SKIP_INSTALL=no
  SKIP_UPDATE=no
  while [ "$1" ]; do
    case $1 in
      --jenkins)
        SETUP_JENKINS=yes
        ;;
      --skip-update)
        SKIP_UPDATE=yes
        ;;
      --skip-install)
        SKIP_INSTALL=yes
        ;;
      *)
        log error "Unknown parameter to ${FUNCNAME}: ${1}"
        exit 1
        ;;
    esac
    shift
  done

  log info "Setup with:"
  log info "* Jenkins: ${SETUP_JENKINS}"
  log info "* Skip apt-get update: ${SKIP_UPDATE}"
  log info "* Skip installation of dependencies: ${SKIP_INSTALL}"

  if [ "${SETUP_JENKINS}" == "yes" ]; then
    sudo mkdir -p /srv/oe
    sudo chown buildslave:buildslave /srv/oe
    cd /srv/oe
  fi

  if [ "${SKIP_INSTALL}" == "no" ]; then
    # Install APT dependencies
    pkg_list="android-tools-fsutils chrpath cpio diffstat gawk libelf-dev libmagickwand-dev \
              libmath-prime-util-perl libsdl1.2-dev libssl-dev python-pip python-requests texinfo \
              vim-tiny virtualenv whiptail"
    if [ "${SKIP_UPDATE}" == "no" ]; then
      if ! log_on_error sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 update; then
        log info "apt update error - try again in a moment"
        sleep 15
        log_on_error sudo DEBIAN_FRONTEND=noninteractive apt-get update || true
      fi
    fi
    if ! log_on_error sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install -y ${pkg_list}; then
      log info "apt install error - try again in a moment"
      sleep 15
      log_on_error sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ${pkg_list}
    fi

    # Install jinja2-cli and ruamel.yaml
    pip install --user --force-reinstall jinja2-cli ruamel.yaml

    install_repo
  fi
}


loeb_init() {
  SYNC=yes
  while [ "$1" ]; do
    case $1 in
      --no-sync)
        SYNC=no
        ;;
      --branch)
        shift; BRANCH=$1
        ;;
      --manifest)
        shift; MANIFEST_URL=$1
        ;;
      *)
        log error "Unknown parameter to ${FUNCNAME}: $1"
        exit 1
        ;;
    esac
    shift
  done
  DEFAULT_MANIFEST_URL=${MANIFEST_URL:-https://github.com/96boards/oe-rpb-manifest.git}
  DEFAULT_BRANCH=${BRANCH:-morty}

  read -e -p "Which branch are we building today? [${DEFAULT_BRANCH}] " branch
  [ -z "${branch}" ] && branch="${DEFAULT_BRANCH}"
  echo "Branch selected: ${branch}"

  read -e -p "Enter manifest URL [${DEFAULT_MANIFEST_URL}] " manifest_url
  [ -z "${manifest_url}" ] && manifest_url="${DEFAULT_MANIFEST_URL}"
  echo "Manifest URL: ${manifest_url}"

  if ! which repo > /dev/null; then
    install_repo
  fi

  repo init -u "${manifest_url}" -b "${branch}"
  if [ "${SYNC}" == "yes" ]; then
    loeb_sync
  fi
}

loeb_sync() {
  log info "Synchronizing..."
  if ! which repo > /dev/null; then
    install_repo
  fi
  repo sync $*
}

loeb_reset() {
  echo "Resetting will remove all unsaved changes and delete untracked files"
  echo "across all repos."
  read -e -p "Are you sure you want to proceed? [y/N] " proceed
  answer=${proceed:0:1}
  if [ "${answer,,}" != "y" ]; then
    echo "Not resetting."
    return
  fi
  dir=$(get_repo_base_dir)
  dir=${dir:-.}
  pushd "${dir}" > /dev/null
  rm -f pinned-manifest-latest.xml
  rm -f pinned-manifest.xml
  rm -f source-manifest.xml
  if [ -d .repo/manifests/ ]; then
    cd .repo/manifests/
    git reset --hard HEAD
    cd "${OLDPWD}"
  fi
  repo forall -c git reset --hard HEAD
  repo forall -c git clean -fdx
  popd > /dev/null
}

# Sauce of the house, used on all recipes
# needs:
# PUB_DEST
# BUILD_NUMBER
sauce_house() {
  # Copies of our manifest
  cp .repo/manifest.xml source-manifest.xml
  repo manifest -r -o pinned-manifest.xml
  MANIFEST_COMMIT=$(cd .repo/manifests && git rev-parse --short HEAD)

  # Record changes since last build, if available
  BASE_URL=${BASE_URL:-http://snapshots.linaro.org}
  if wget -q ${BASE_URL}${PUB_DEST/\/${BUILD_NUMBER}\//\/latest\/}/pinned-manifest.xml -O ${BASE_DIR}/pinned-manifest-latest.xml; then
    repo diffmanifests ${BASE_DIR}/pinned-manifest-latest.xml ${BASE_DIR}/pinned-manifest.xml > ${BASE_DIR}/manifest-changes.txt
  else
    log warning "Latest build published does not have pinned-manifest.xml. Skipping diff report."
  fi

  # the setup-environment will create auto.conf and site.conf
  # make sure we get rid of old config.
  # let's remove the previous TMPDIR as well.
  # we want to preserve build/buildhistory though.
  rm -rf conf ${BUILD_DIR}/conf ${BUILD_DIR}/tmp-*glibc/

  # Accept EULA if/when needed
  export EULA_dragonboard410c=1
  export EULA_stih410b2260=1
  sh setup-environment ${BUILD_DIR}

  cd ${BUILD_DIR}
  # Add job BUILD_NUMBER to output files names
  cat << EOF >> conf/auto.conf
IMAGE_NAME_append = "-${BUILD_NUMBER}"
KERNEL_IMAGE_BASE_NAME_append = "-${BUILD_NUMBER}"
MODULE_IMAGE_BASE_NAME_append = "-${BUILD_NUMBER}"
DT_IMAGE_BASE_NAME_append = "-${BUILD_NUMBER}"
BOOT_IMAGE_BASE_NAME_append = "-${BUILD_NUMBER}"
EOF

  # get build stats to make sure that we use sstate properly
  cat << EOF >> conf/auto.conf
INHERIT += "buildstats buildstats-summary"
EOF
}

# Sauce for Reference Platform builds
sauce_rpb() {
  dir=$(get_repo_base_dir)
  dir=${dir:-.}
  cd "${dir}"

  sauce_house
}

# Sauce for Linux Kernel Functional Testing builds
# needs:
# KERNEL_RECIPE
# KERNEL_VERSION
# SRCREV_kernel
sauce_lkft() {
  dir=$(get_repo_base_dir)
  dir=${dir:-.}
  cd "${dir}"

  sauce_house

  # Set the kernel to use
  distro_conf=$(find ../layers/meta-rpb/conf/distro -name rpb.inc)
  cat << EOF >> ${distro_conf}
PREFERRED_PROVIDER_virtual/kernel = "${KERNEL_RECIPE}"
EOF

  case "${KERNEL_RECIPE}" in
    linux-hikey-aosp|linux-generic-android-common-o*|linux-generic-lsk*|linux-generic-stable*)
      cat << EOF >> ${distro_conf}
PREFERRED_VERSION_${KERNEL_RECIPE} = "${KERNEL_VERSION}+git%"
EOF
      ;;
  esac

  # Use meta-oe version, required for mosh
  cat << EOF >> ${distro_conf}
PREFERRED_VERSION_protobuf = "2.6.1+git%"
PREFERRED_VERSION_protobuf-native = "2.6.1+git%"
EOF

  # Set the image types to use
  cat << EOF >> ${distro_conf}
IMAGE_FSTYPES_remove = "ext4 iso wic"
EOF

  case "${KERNEL_RECIPE}" in
    linux-*-aosp|linux-*-android-*)
      cat << EOF >> ${distro_conf}
CONSOLE = "ttyFIQ0"
EOF
      ;;
  esac

  cat << EOF >> ${distro_conf}
KERNEL_ALT_IMAGETYPE_remove_stih410-b2260 = "vmlinux"
EOF

  # Mali GPU driver fails to build
  # error: implicit declaration of function 'copy_from_user'
  # [-Werror=implicit-function-declaration]
  # Ignore the whole gpu MACHINE_FEATURES mechanism
  stih410_b2260_conf=$(find ../layers/meta-st-cannes2/conf/machine -name stih410-b2260.conf ||:)
  test -e "${stih410_b2260_conf}" && sed -i -e '/gpu/d' ${stih410_b2260_conf}

  # Include additional recipes in the image
  [ "${MACHINE}" = "am57xx-evm" -o "${MACHINE}" = "stih410-b2260" ] || extra_pkgs="numactl"
  cat << EOF >> conf/local.conf
CORE_IMAGE_BASE_INSTALL_append = " kernel-selftests kselftests-mainline kselftests-next libhugetlbfs-tests ltp ${extra_pkgs}"
CORE_IMAGE_BASE_INSTALL_append = " python python-misc python-modules python-numpy python-pexpect python-pyyaml"
CORE_IMAGE_BASE_INSTALL_append = " git mosh-server parted packagegroup-core-buildessential packagegroup-core-tools-debug tzdata"
EOF

  # Override cmdline
  cat << EOF >> conf/local.conf
CMDLINE_remove = "quiet"
EOF

  # Remove recipes:
  # - docker to reduce image size
  cat << EOF >> conf/local.conf
RDEPENDS_packagegroup-rpb_remove = "docker"
EOF

  cat << EOF >> conf/local.conf
DEFAULTTUNE_intel-core2-32 = "core2-64"
SERIAL_CONSOLES_remove_intel-core2-32 = "115200;ttyPCH0"
SERIAL_CONSOLES_append_dragonboard-410c = " 115200;ttyMSM1"
SERIAL_CONSOLES_append_hikey = " 115200;ttyAMA2"
EOF

  # Enable lkft-metadata class
  cat << EOF >> conf/local.conf
INHERIT += "lkft-metadata"
LKFTMETADATA_COMMIT = "1"
EOF

  # Remove systemd firstboot and machine-id file
  # Backport serialization change from v234 to avoid systemd tty race condition
  mkdir -p ../layers/meta-96boards/recipes-core/systemd/systemd
  wget -q http://people.linaro.org/~fathi.boudra/backport-v234-e266c06-v230.patch \
    -O ../layers/meta-96boards/recipes-core/systemd/systemd/backport-v234-e266c06-v230.patch
  cat << EOF >> ../layers/meta-96boards/recipes-core/systemd/systemd/e2fsck.conf
[options]
# This will prevent e2fsck from stopping boot just because the clock is wrong
broken_system_clock = 1
EOF
  backported_path="file://backport-v234-e266c06-v230.patch"
  systemd_recipe=$(ls ../layers/openembedded-core/meta/recipes-core/systemd/systemd_*.bb)
  [ "${systemd_recipe}" == "systemd_234.bb" ] && backported_patch=""
  cat << EOF >> ../layers/meta-96boards/recipes-core/systemd/systemd_%.bbappend
FILESEXTRAPATHS_prepend := "\${THISDIR}/\${PN}:"

SRC_URI += "\\
    ${backported_patch} \\
    file://e2fsck.conf \\
"

PACKAGECONFIG_remove = "firstboot"

do_install_append() {
    # Install /etc/e2fsck.conf to avoid boot stuck by wrong clock time
    install -m 644 -p -D \${WORKDIR}/e2fsck.conf \${D}\${sysconfdir}/e2fsck.conf

    rm -f \${D}\${sysconfdir}/machine-id
}

FILES_\${PN} += "\${sysconfdir}/e2fsck.conf "
EOF

  # Update kernel recipe SRCREV
  kernel_recipe=$(find ../layers/meta-96boards -name ${KERNEL_RECIPE}_${KERNEL_VERSION}.bb)
  sed -i "s|^SRCREV_kernel = .*|SRCREV_kernel = \"${SRCREV_kernel}\"|" ${kernel_recipe}

}

sauce_lhg() {
  :
}

loeb_apply() {
  if [ -z "${MACHINE}" -o -z "${DISTRO}" ]; then
    loeb_config
  fi
  sauce_rpb
cat << EOF >> ${BASE_DIR}/env-loeb
set -a
MACHINE=${MACHINE}
DISTRO=${DISTRO}
set +a
. setup-environment ${BUILD_DIR}
EOF
  log info "Done. You can now run:"
  log info "  source env-loeb"
}

update_config() {
  item=$1; shift
  value="$*"
  if [ -f "${CONFIG_FILE}" ] && grep -q ^"${item}=" "${CONFIG_FILE}"; then
    sed -i -e "s|^${item}=.*|${item}=${value}|" "${CONFIG_FILE}"
  else
    echo "${item}=${value}" >> "${CONFIG_FILE}"
  fi
}

show_config() {
  if [ -f ${CONFIG_FILE} ]; then
    if [ $# -eq 0 ]; then
      log info "Configuration:"
      cat "${CONFIG_FILE}"
    else
      log info "[config] $(grep ^$1= ${CONFIG_FILE})"
    fi
  fi
}

loeb_config() {
  DEFAULT_MACHINE=hikey
  DEFAULT_DISTRO=rpb

  read -e -p "Machine to build for? [${DEFAULT_MACHINE}] " machine
  [ -z "${machine}" ] && machine="${DEFAULT_MACHINE}"
  echo "Selected machine: ${machine}"
  update_config MACHINE "${machine}"
  export MACHINE="${machine}"

  read -e -p "Distro to build? [${DEFAULT_DISTRO}] " distro
  [ -z "${distro}" ] && distro="${DEFAULT_DISTRO}"
  echo "Selected distro: ${distro}"
  update_config DISTRO "${distro}"
  export DISTRO="${distro}"
}


# START HERE
BASE_DIR=$(get_repo_base_dir)
BASE_DIR=${BASE_DIR:-.}
CONFIG_FILE="${BASE_DIR}/.loeb.config"
BUILD_DIR=build
BUILD_NUMBER=1337
if [ -f "${CONFIG_FILE}" ]; then
  log info "Reading config from ${CONFIG_FILE}"
  set -a
  source "${CONFIG_FILE}"
  set +a
fi

if [ $# -lt 1 ]; then
  usage
  exit 0
fi

action=$1; shift
case ${action} in
  apply)
    loeb_apply $*
    ;;
  config)
    loeb_config $*
    ;;
  init)
    loeb_init $*
    ;;
  reset)
    loeb_reset $*
    ;;
  setup)
    loeb_setup $*
    ;;
  sync)
    loeb_sync $*
    ;;
  *)
    usage
    ;;
esac

